# -*- coding: utf-8 -*-
"""ghadah1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z6jEw6-J0oH-vNELkM8rfbZMA8I7yTwC
"""

#استدعاء المكتبات
import pandas as pd
from google.colab import files

# 1. إظهار زر "Choose Files" لرفع الملف من سطح المكتب مباشرة
uploaded = files.upload()

# 2. قراءة الملف بعد رفعه مباشرة في الـ DataFrame
df = pd.read_csv('pandas
matplotlib
openpyxl.csv')

df.info()

# لمعرفة عدد القيم المفقودة في كل عمود
df.isnull().sum()

df['Years of Experience'] = df['Years of Experience'].fillna(df['Years of Experience'].mean())

# معرفة عدد الصفوف المكررة
df.duplicated().sum()

# حذف الصفوف المكررة والإبقاء على النسخة الأولى فقط
df = df.drop_duplicates()

df

# تحويل عمود إلى نوع رقمي (Integer)
df['Years of Experience'] = df['Years of Experience'].astype(int)

df.info()

# تحويل العمود وتوحيد صيغته تلقائياً
df['Date Hired'] = pd.to_datetime(df['Date Hired'], format='mixed', dayfirst=True)

df

# 1. حساب قيمة الوسيط لعمود سنوات الخبرة
# (تلقائياً يتجاهل Pandas القيم المفقودة أثناء الحساب)
median_experience = df['Years of Experience'].median()

# 2. تعويض القيم المفقودة بالقيمة المحسوبة
df['Years of Experience'] = df['Years of Experience'].fillna(median_experience)

# لمعرفة عدد القيم المفقودة في كل عمود
df.isnull().sum()

import numpy as np

# 1. تحويل أي مسافات أو نصوص فارغة في عمود "مستوى الخبرة" إلى NaN
df['Experience Level'] = df['Experience Level'].replace(r'^\s*$', np.nan, regex=True)

# 2. إيجاد مستوى الخبرة الأكثر تكراراً (المِنوال)
most_frequent_level = df['Experience Level'].mode()[0]

# 3. تعويض قيم NaN بمستوى الخبرة الأكثر تكراراً
df['Experience Level'] = df['Experience Level'].fillna(most_frequent_level)

# لمعرفة عدد القيم المفقودة في كل عمود
df.isnull().sum()

import numpy as np

# 1. تحويل أي مسافات أو نصوص فارغة في عمود "مستوى الخبرة" إلى NaN
df['City'] = df['City'].replace(r'^\s*$', np.nan, regex=True)

# 2. إيجاد مستوى الخبرة الأكثر تكراراً (المِنوال)
most_frequent_City = df['City'].mode()[0]

# 3. تعويض قيم NaN بمستوى الخبرة الأكثر تكراراً
df['City'] = df['City'].fillna(most_frequent_City)

# لمعرفة عدد القيم المفقودة في كل عمود
df.isnull().sum()

#احصاء وصفي
df.describe()

#حجم البيانات
df.shape

#الصفوف المكررة
df.duplicated()

#أول ٥ اسطر
df.head()

#أول ٥ اسطر
df.tail()

df['Years of Experience'] = df['Years of Experience'].replace(-1, median_experience)

#أول ٥ اسطر
df.head()

#حفظ الجدول
df.to_csv('job_salaries_raw.csv', index=False)

df.sort_values('Salary', ascending=False)

#لاتنسوا تغيير الكمية qyuantit#حساب الوسيط و التعبئة
md_Salary = df['Salary'].median()
df['Salary'] = df['Salary'].fillna(md_Salary)

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

#مخطط صندوقي
sns.boxplot(y=df['Salary'])
plt.title("Salary-avg")
plt.show()

#مخطط العد والتكرار
sns.countplot(x='Experience Level', data=df)
plt.title("Experience Level")
plt.show()

# 1. توحيد النص (جعل أول حرف كابيتال وإزالة أي مسافات زائدة)
df['City'] = df['City'].str.strip().str.capitalize()

# 2. إعادة حساب التكرارات بعد التوحيد
City_counts = df['City'].value_counts()

# 3. رسم المخطط الدائري الموحد
plt.pie(City_counts,
        labels=City_counts.index,
        autopct='%1.1f%%',
        colors=['skyblue', 'pink'])

plt.title("City distribution")
plt.show()



